### ISSUE TITLE
Can't change default sorting method

### ISSUE THREAD

**Issue by MeltedBu11et** [Torrunt/vimage#28]
You can't change the default sorting method, it always sets back to Name.

**Comment by Torrunt** [comment]
I've never had that problem. Could I get some more details?

Do you mean the checkbox in the context menu always goes back to Name after clicking another method? Does it always happen no matter what folder the images you are viewing are in?

**Comment by Torrunt** [comment]
I never got an answer back on this but I think what @MeltedBu11et was saying was that when you open vimage again it always defaults the sorting method to name. That wasn't the intention of that context menu but I think having an option in the settings menu to set your default sorting method might be a good idea.

I also would love to have a way to tell how windows is sorting the current folder and make vimage sort the same way. No idea how you would go about that though.

**Comment by Torrunt** [comment]
Added default sorting options to vimage_settings.exe in https://github.com/Torrunt/vimage/commit/dc96e1b997dfcd41f65c58d441f56eb04c229a69

**Comment by Torrunt** [comment]
This issue is closed but I thought I better mention that other sorting improvements were made in this commit: https://github.com/Torrunt/vimage/commit/ba4f2ea6919183e60b553517fc663a6a271188c4
