### ISSUE TITLE
vimage crashes when closing GIFs

### ISSUE THREAD

**Issue by zpankr** [Torrunt/vimage#29]
I installed vimage on virtually every computer I own and help setup, and recently did so on my Work computer. It's all fine and dandy except it crashes when, after opening an animated GIF, I right click and close.

Here's a small video exemplifying it with a random assortment of images and gifs.

https://dl.dropboxusercontent.com/u/2111732/ShareX/Work/2016-01-04_20-54-43.webm

**Comment by Torrunt** [comment]
Hmmmm. I thought maybe it had to do with Windows 7 but I just tried vimage out on my laptop which still has Windows 7 on and I didn't have this problem.

Could you try this version of vimage out? It should show an error report when it crashes.
https://dl.dropboxusercontent.com/u/7113767/vimage/vimage_version8_crashReporterIncluded.zip

**Comment by zpankr** [comment]
Just tried it out with the crashReporter version. It still crashes and
there's no crash report anywhere I could find..
Here's a video
https://dl.dropboxusercontent.com/u/2111732/ShareX/Work/2016-01-05_22-10-02.webm

**Comment by Torrunt** [comment]
Damn. Alright, see if this one fixes the problem or at least shows a crash report.
https://dl.dropboxusercontent.com/u/7113767/vimage/vimage_version8_crashReporterIncluded2.zip

**Comment by zpankr** [comment]
Only had the chance to try it now, it fixed it! What was the problem?

**Comment by Torrunt** [comment]
Wow, surprised that fixed it. All I did was made it close the window before it broke out of the update loop.

https://github.com/Torrunt/vimage/commit/962b6931e9726a9170d70848ef1ba2da84a55390
