### ISSUE TITLE
Opening an image with the same size as the desktop makes it fullscreen; context menu and cursor are invisible

### ISSUE THREAD

**Issue by ottworks** [Torrunt/vimage#32]

**Comment by Torrunt** [comment]
Weird, I've never had this happen to me. My screen's resolution is 1920x1080 and when I open a 1920x1080 image I can still see the cursor and use the context menu.

Does it happen all the time and what resolution is your screen/image?

**Comment by 0tt** [comment]
1080p. I think it's an issue with SDL because it happens in Love2D games as
well.

**Comment by ottworks** [comment]
Would you mind supplying new builds now that this issue is fixed?

**Comment by Torrunt** [comment]
I'll be releasing version 14 soon. I just had another thing I wanted to do before I release it.

**Comment by Torrunt** [comment]
Version 14 is out now: https://github.com/Torrunt/vimage/releases/tag/v14

**Comment by Torrunt** [comment]
Really? If that exclusive fullscreen fix didn't fix it, I have no idea what will. It's never happened to me so I can't really debug it.

I'll re-open the issue, if someone else has the same issue and thinks they know how to fix it, go ahead.

**Comment by ottworks** [comment]
I guess I can describe the issue a little more.
Upon opening a 1080p image, the screen flashes black shortly. Right clicking does not show the context menu (it's invisible), however you can still interact with it (such as moving the mouse down a bit and clicking to close the image). From here, if you zoom out and back in, the image behaves correctly. If you instead try to alt-tab, the image will go invisible. The context menu works correctly though when alt-tabbing back in.
