### ISSUE TITLE
Animated GIFs only plays when moving the image

### ISSUE THREAD

**Issue by 0-l** [Torrunt/vimage#33]
I just installed this program and I absolutely love it for its simplicity. But I have a problem when viewing animated GIFs, they just won't play unless I move the image around. I'm not sure if this is an option on the settings, but I'd be glad if there was a way to "fix" this.
![gif-issue](https://i.imgur.com/khqp83D.gif)

Also, sometimes using `ESC` to close the image doesn't work unless I `alt + tab` and try it again, and paginating through images on a big folder freezes the program, but I suppose this is a different issue.

**Comment by Torrunt** [comment]
That shouldn't happen. What OS are you using? 

ESC only works if the image is in focus. Was it sometimes not working even when they were in focus?

When does it freeze and for how long? when you press a key to go to the next image? It might hang for a bit if you try to go to the next image if Windows is still currently sorting the folder based on it's default sorting method. Does it still freeze if you change the default sorting method for vimage to something other than FOLDER?.

**Comment by 0-l** [comment]
I'm using Windows. 

The ESC key didn't work when canceling going to the next image.

The freezing behaviour went to normal once I restarted the "Windows Explorer" task, although changing the default sorting to "Date Created" seemed to make it slightly faster.

I tried disabling background tasks like f.lux and Sharex to see if anything was interfering with the program, but had no success.

I also noticed that the frames go forward a bit when I right click the image.
![gif-issue2](https://i.imgur.com/3YpLjyf.gif)

Thanks for the quick reply.

**Comment by 0-l** [comment]
I sort of fixed the issue.
I don't know why, but apparently using the High Contrast theme is what causes this behaviour, which is unfortunate because I really dislike the white colors of the default theme. But anyways, I'm not sure if you'll ever look into this issue in the future, but I'll just associate the .gif file to open with the default photo viewer for now.

I think this issue can be closed, thanks for the help.

**Comment by Torrunt** [comment]
So do animated gifs start working fine for you if you change your High Contrast theme back to None?
I just tried turning on High Contrast and animated gifs in vimage still worked fine for me.

**Comment by 0-l** [comment]
`So do animated gifs start working fine for you if you change your High Contrast theme back to None?`
Not sure what you mean by changing it to 'none', but if you're referring to changing the theme to the default one, then yes.

**Comment by Torrunt** [comment]
I mean in the high-contrast settings for windows:
![image](https://user-images.githubusercontent.com/830354/35195896-321fe634-ff05-11e7-82ba-3535fd4dadf5.png)

I can't seem to replicate the problem on my system. If you have Visual Studio and want to try and debug it yourself the animated gif redraw code is located here: https://github.com/Torrunt/vimage/blob/79d2305c16ce272c6410e544a5fca5ee4bafcd39/vimage/Source/ImageViewer.cs#L250-L257

**Comment by 0-l** [comment]
Oh, it seems like my windows version still hasn't received the Fall Creators update yet, I still have the old windows 7 theme page.
![theme-page](https://i.imgur.com/IRhS1Vq.png)
I do have Visual Studio, even though I have very little knowledge of C#, I'll give it a try.
