### ISSUE TITLE
Adjustable Transparency

### ISSUE THREAD

**Issue by 0tt** [Torrunt/vimage#34]
It'd be really nice if there were hotkeys for adjusting transparency of an image. I wanted to overlay a bunch of schedules to check for openings, and it sounds like the kind of thing vimage would be able to do.

**Comment by Torrunt** [comment]
Sounds like a neat feature.

Added it in https://github.com/Torrunt/vimage/commit/86b2b1f6265db0575673867abeca982be9c18fbd

You can now press T (default) to toggle transparency or hold Y (default) and use the mouse wheel to adjust it.

**Comment by Torrunt** [comment]
Here's the updated version of vimage built if you wanted to try it out without building it yourself:
[vimage_version11a.zip](https://github.com/Torrunt/vimage/files/1654714/vimage_version11a.zip)
