### ISSUE TITLE
Unable to load DLL 'DevIL.dll' error

### ISSUE THREAD

**Issue by reggiegreenbud** [Torrunt/vimage#35]
I had to do a fresh windows 10 install, now i get an error when trying to use vimage.
`Unable to load DLL 'DevIL.dll': The specified module could not be found. (Exception from HRESULT: `0x8007007E)``
I have same windows 10 installed as before, same programs, same everything. 

any suggestions please?

**EDIT**
issue resolved itself after i installed photoshop

**Comment by Torrunt** [comment]
Weird. I wonder if DevIL needed some sort of redistributable I didn't know about. If someone else has this problem try installing the Visual C++ Redistributable: https://www.microsoft.com/en-au/download/details.aspx?id=48145
