### ISSUE TITLE
Option for scroll wheel to bind next/previous rather than zoom

### ISSUE THREAD

**Issue by PixelEater** [Torrunt/vimage#36]
I didn't see any way to enable my preferred way of browsing an image directory, simply by using the scroll wheel to move backwards and forwards. It would also be nice if I could tell directories not to loop on the first and last image.

**Comment by Torrunt** [comment]
Done. I also added support for using key modifiers with mouse buttons/scrolling (dc60e3d8154e242343b35f53ca01f18a507d215c). So now you can bind SCROLLUP/DOWN to change images and SHIFT+SCROLLUP/DOWN for zooming for example.
