### ISSUE TITLE
Proposal for an optional "ugly interface" mode

### ISSUE THREAD

**Issue by PixelEater** [Torrunt/vimage#38]
I have always been a fan of having a minimal amount of GUI around my image viewer. Disabling it completely doesn't always suit the type of work I'm doing, like sorting images versus relaxing. It really depends. I wouldn't want to bore you with all the reasons, but trust me I genuinely could. One that inspired me to open this issue is the convenience of confirming a file name in just one glance. I believe currently right click > "Open file location" is about it for ways of doing this. So of course you don't have to enable this by default, but how about a mode that looks just like this?

![why not](https://user-images.githubusercontent.com/10372471/38301156-5e7dfb74-37c4-11e8-9dea-f168b3a0b491.png)

I could even picture a third option which adds Windows' default shading underneath the completely borderless images, but I'm entirely unsure if Windows would even allow it. It would provide some relief to conundrums like viewing a white borderless image on a white background, etc.

**Comment by Torrunt** [comment]
I guess I could add that in as an option. Pretty simple to add:
![snip1](https://user-images.githubusercontent.com/830354/38305215-a0d25572-383e-11e8-820c-c20c5ae6d335.PNG)
It would require some debugging though as having the titlebar/border causes problems with dragging and image transparency. I'll attempt to fix those and implement it later this week.

I also added a quick way to put the current file name in the Context Menu with https://github.com/Torrunt/vimage/commit/fb8d4146a995ea258496dca8f910b194d51249dd . You can then rename "Open file location" or whatever to [filename].

**Comment by PixelEater** [comment]
Yeah I'm sure transparency would need to default to having a background and that fullscreen would be a thing. I just realized I'm leaning back in my chair and had to lean forward to hit escape with my left hand. Can't be as lazy without this feature!

You're gonna love me, as I definitely have a small series of ideas or things I noticed about this program. And I'm hunting for a great image viewer, which this is well on its way to being! But I already love you too for responding so promptly and being open to ideas, unlike *cough* IRFANVIEW *cough* for instance.

I just noticed Alt+F4 doesn't work if you've dragged a window. That's a curious one.

**Comment by Torrunt** [comment]
What do you mean by you had to lean forward to hit esc? You could just right-click -> close or bind a mouse button to close.

Yeah, that's fine. Feel free to submit new issues if you have ideas or found any problems.

Alt-F4 works fine for me. It doesn't work if your currently dragging though, is that what you meant?

**Comment by PixelEater** [comment]
Right click close of course is an option, but still less lazy than hitting X. I do get what you mean about binding it, though I'd have to sacrifice my beautifully redundant back or forward button, and not everyone has em. At any rate, I'm still able to confirm that this is happening: I drag the window once and alt+f4, then I drag it a second time and alt+f4 works. Then sometimes I can drag the window two or more times and land on an interval where it still resists alt+f4. Esc basically works no matter what. Win10 64 here.

**Comment by Torrunt** [comment]
Does it just not work at all or can you just press Alt-F4 again and it works? I only managed to get it to not work a few times by messing around but if I just press it a second time it closes. It's not really a problem anyway if the normal close buttons works.

**Comment by Torrunt** [comment]
I've added an option to show the title bar. There's still a problem at the moment though when you open a thin image or resize an image too small. Will have to limit how small/thin images can be when Title Bar is on.

I'll also add a function to toggle the title bar on/off later, so you can put that in the context menu or bind a key to it.

**Comment by PixelEater** [comment]
Yeah as far as I know the smallest width a Windows 10 window should handle is 120 before the close and minimize buttons are completely hitting the program icon. It is normal for most image viewers to have a minimum width. Height should be able to go much smaller, at least around 32 if you're even counting the title bar.

Looking forward to seeing how the first attempt comes out. Thanks for entertaining it.
