### ISSUE TITLE
Transparent images have black background

### ISSUE THREAD

**Issue by ottworks** [Torrunt/vimage#42]
Thank you for maintaining vimage!
Some time in the last few months transparent images stopped appearing transparent. I've tried reverting to previous versions of vimage, but they all have this problem.

![image](https://user-images.githubusercontent.com/5253130/56543872-a3569080-6527-11e9-8829-ac9b60bf9531.png)

**Comment by Torrunt** [comment]
Weird. Transparency still works fine for me.

Does turning transparency on/off do anything? What about changing the different background colour in the settings?

Have you tried updating Windows and/or your graphics drivers?
