### ISSUE TITLE
Zooming causes off-screen image parts to be displayed wrongly until zoomed again while on-screen

### ISSUE THREAD

**Issue by Inari-Whitebear** [Torrunt/vimage#47]
Sometimes I have a big image and zoom in on something specific, but then also want to pan around to other parts of it. However, zooming seems to displace parts of the image that are currently not visible on the screen, I then have to zoom again once they are visible to fix that, which can be a bit annoying.

Example:

1. just opened
![firefox_KdqsQsWi2Z](https://user-images.githubusercontent.com/1077971/80865293-a2068a80-8c88-11ea-81c2-ebff72723788.png)

2. pulled offscreen and zoomed out
![firefox_NpxqF6sD4b](https://user-images.githubusercontent.com/1077971/80865299-acc11f80-8c88-11ea-99ef-63828b749db3.png)

3. pulled back on-screen
![firefox_Qs9G67sJbU](https://user-images.githubusercontent.com/1077971/80865303-b21e6a00-8c88-11ea-99e2-d00aeaa7cff5.png)

4. fixed after zooming again
![firefox_RN9qmiunSl](https://user-images.githubusercontent.com/1077971/80865306-b6e31e00-8c88-11ea-8f9a-c98d6f668db7.png)

**Comment by Torrunt** [comment]
I've noticed this recently too, It's pretty annoying. For some reason zooming just started bugging out a while ago... Not sure when, maybe after some particular Windows update.

I haven't gotten around to debugging it yet though.
