### ISSUE TITLE
didn't work in win10?

### ISSUE THREAD

**Issue by jieYM** [Torrunt/vimage#48]
Hi, I can't launch vimage.exe in win10, get nothing change, no window display, no error message. Is it didn't support win10？

**Comment by Torrunt** [comment]
Yes, it supports Windows 10.

You can't open vimage.exe directly; you need to open an image with it. Change your default image viewer to vimage or if you just want to quickly test it; you can drag an image onto vimage.exe.

**Comment by jieYM** [comment]
> Yes, it supports Windows 10.
> 
> You can't open vimage.exe directly, you need to open an image with it. Change your default image viewer to vimage or if you just want to quickly test it; you can drag an image onto vimage.exe.

It worked! Thanks a lot, and I love it very much. Thanks for develop something like that.
