### ISSUE TITLE
Can't open vimage.

### ISSUE THREAD

**Issue by Max-Spec** [Torrunt/vimage#50]
As I reset my PC, trying to open vimage leads me to encounter this error message:
`Не удается загрузить DLL "DevIL.dll": Не найден указанный модуль. (Исключение из HRESULT: 0x8007007E)`

**Comment by Torrunt** [comment]
Is this with a fresh install of vimage? Is the `DevIL.dll` file in the vimage folder?

**Comment by Max-Spec** [comment]
At first it wasn't a new install but it was the same version as it currently is. It had the .dll as well, but couldn't see it for whatever reason. Now I reinstalled it and it... works again.

**Comment by Torrunt** [comment]
Weird. At least it works now.

**Comment by jak3-taylor** [comment]
Same issue. Fresh install of Windows 10 21H2. Worked perfectly this setup before but not with the fresh install.

```
System.DllNotFoundException

Unable to load DLL 'DevIL.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

   at DevIL.Unmanaged.IL.ilInit()
   at DevIL.Unmanaged.IL.Initialize()
   at vimage.ImageViewer..ctor(String file, String[] args)
   at vimage.Program.Main(String[] args)
```

DevIL.dll is in the folder with vimage. I've tried opening vimage with an image. I have Visual C++ Redistributable installed. vimage_settings opens fine.

Anyone have any ideas? Thanks.
