### ISSUE TITLE
The picture is in the center of the screen, is it possible?

### ISSUE THREAD

**Issue by Bondualf** [Torrunt/vimage#51]
I want the picture to always open in the middle of the screen, but not on the side. Every time the picture goes somewhere

PS_Sorry, I do not know English, I use Google translator..

**Comment by Bondualf** [comment]
Thanks a lot. It really works. Vimage, this is the best image at this planet. I used to use JpegView. But Vimage is amazing, it is without a frame - this is a real find for me. Now I deleted JpegView, instead of it now Vimage.

 :^)

Thank you!

**Comment by Bondualf** [comment]
Если вы добавите поддержку иностранных языков, многие люди узнают о вашей программе. И не будут задавать простых вопросов. 

Большое спасибо. Я желаю развития проекту. Я посоветую своим друзьям использовать Vimage, Это лучший вьювер, который я видел за свою жизнь.

:^)

**Comment by Torrunt** [comment]
Language support is a good idea. Made when I have some free time.
